name: My Fist Work flow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My Fist hub actions"
        
        - name: list files
          run: ls
        
        - name: Read files
          run: cat README.md