name: Generate Ascii code

on: push

jobs:
  acsii_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout apps
      uses: actions/checkout@v7

    - name: list the file
      run: ls -lrt    

    - name: Execute the script
      run: |
        chmod +x ascii_workflow.sh
        ./ascii_workflow.sh

